service: etl-group-3

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  iam:  
    role:
      permissionsBoundary: arn:aws:iam::351115496094:policy/ScopePermissions

resources:
  Resources:
    IamRoleCustomResourcesLambdaExecution:
      Type: AWS::IAM::Role
      Properties:
        PermissionsBoundary: arn:aws:iam::351115496094:policy/ScopePermissions

functions:
  etl3:
    handler: src/handler.lambda_handler
    layers: arn:aws:lambda:eu-west-1:351115496094:layer:final-project-data-producer-dev-python-requirements:1
    vpc:
      securityGroupIds:
        - sg-0afcfd2a983b80407
      subnetIds:
        - subnet-0f0145739a0011749
    events:
      - s3:
          bucket: delon3-team-3-bucket
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - suffix: .csv
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - s3:GetObject
          - s3:ListBucket
        Resource:
          - arn:aws:s3:::delon3-team-3-bucket
          - arn:aws:s3:::delon3-team-3-bucket/*

package:
  include: 
    - src/**
  exclude:
    - "*"
    - "*/**" 
    - throwaway_code/**
  individually: true
  excludeDevDependencies: false 