service: etl-group-3-sqs

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  iam:  
    role:
      permissionsBoundary: arn:aws:iam::351115496094:policy/ScopePermissions

resources:
  Resources:
    IamRoleCustomResourcesLambdaExecution:
      Type: AWS::IAM::Role
      Properties:
        PermissionsBoundary: arn:aws:iam::351115496094:policy/ScopePermissions

functions:
  extract_transform:
    handler: src/sqs_extract_transform.lambda_handler
    role: "arn:aws:iam::351115496094:role/etl-group-3-dev-etl3-eu-west-1-lambdaRole"
    timeout: 300
    layers: 
      - Ref: PythonRequirementsLambdaLayer
    events:
      - s3:
          bucket: delon3-team-3-bucket
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - suffix: .csv
  
  load:
    handler: src/sqs_load.lambda_handler
    role: "arn:aws:iam::351115496094:role/etl-group-3-dev-etl3-eu-west-1-lambdaRole"
    timeout: 300
    layers: 
      - Ref: PythonRequirementsLambdaLayer
    vpc:
      securityGroupIds:
        - sg-0afcfd2a983b80407
      subnetIds:
        - subnet-0f0145739a0011749
        - subnet-0b5a9c546fd7ca400
        - subnet-026cbc956a6cc5592
    environment:
      redshift_cluster: "redshiftcluster-jlqz8zhcuit6"
      redshift_host: "172.31.71.76"
      redshift_database: "team-3-db"
      redshift_port: "5439"
      redshift_user: "awsuser"
package:
  include: 
    - src/**
  exclude:
    - "*"
    - "*/**" 
    - throwaway_code/**
  individually: true
  excludeDevDependencies: false 

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer: true
