service: etl-group-3

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  iam:  
    role:
      permissionsBoundary: arn:aws:iam::351115496094:policy/ScopePermissions

functions:
  etl2:
    handler: src/etl-group3/handler.lambda_handler
    events:
      - s3:
          bucket: team3testbucket
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

package:
  include: 
    - src/**
  exclude:
    - "*"
    - "*/**" 
  individually: true
  excludeDevDependencies: false 